title: <p align="center"> Vimala K S </p>
logo: /assets/img/vimala.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  
  <br>   
  I'm working on Data Science, Computer Vision, Image Processing, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  <br>
  </p>
theme: jekyll-theme-minimal
